# Generated by Django 4.2.3 on 2023-08-04 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djform',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 4, 13, 43, 3, 791148)),
        ),
    ]
