# Generated by Django 4.2.3 on 2023-08-04 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djform', '0002_djform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='djform',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 4, 13, 46, 15, 397926)),
        ),
        migrations.AlterField(
            model_name='djform',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 4, 13, 46, 15, 397926)),
        ),
    ]
