# Generated by Django 4.2.3 on 2023-08-05 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djform', '0003_djform_updated_at_alter_djform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='djform',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djform',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 12, 16, 3, 163385)),
        ),
        migrations.AlterField(
            model_name='djform',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 12, 16, 3, 163385)),
        ),
    ]
