# Generated by Django 4.2.3 on 2023-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djform', '0004_djform_word_count_alter_djform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djform',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2023-08-05, 17:02:12'),
        ),
        migrations.AlterField(
            model_name='djform',
            name='updated_at',
            field=models.DateTimeField(blank=True, default='2023-08-05, 17:02:12'),
        ),
    ]
