# Generated by Django 4.2.3 on 2023-07-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='doj',
            field=models.DateField(null=True),
        ),
    ]
