# Generated by Django 4.2.3 on 2023-07-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_emp_doj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='age',
        ),
    ]
