# Generated by Django 4.2.3 on 2023-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_emp_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
